rendering
style 
    ^ 'body {
    color: #222;
	 margin:0;
    font-size: 110%;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
header {
	height: 5vh;
	 padding: 5px;
	 border-bottom: 2px solid black;
	 background-color: cornflowerblue;
	 color: white;
	 display: flex;
    justify-content: space-between;
    align-items: center;
}
h1 {
    color: #111;
    font-size: 2em;
    font-weight: normal;
    margin-bottom: 0.5em;
}
#content { height: 86.7vh;
padding-left: 10px; padding-top: 10px;}
footer {
	height: 2vh;
	border-top: 2px solid black;
	padding: 5px;
	color: white;
	background-color: cornflowerblue;
}'