styles
style 
    ^ 'body {
    color: #222;
	 margin:0;
    font-size: 110%;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
header {
	height: 5vh;
	 padding: 5px;
	color: white;
	 border-bottom: 2px solid black;
	 background-color: cornflowerblue;
	 display: flex;
    justify-content: space-between;
    align-items: center;
}
h1 {
    font-size: 2em;
color: #111;
    font-weight: normal;
    margin-bottom: 0.5em;
}
#content {
	display: flex;
	justify-content: space-between;
}
#agregar {
	padding-top: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
    cursor: pointer;
}
#agregar > span {
	 background-color: lightpink;
    border-radius: 10px;
    width: 20px;
    font-size: 22px;
    height: 20px;
    display: flex;
    justify-content: center;
    align-items: center; }
a { height: 100%; text-decoration: none;}
form { padding: 5px;}
footer {
	height: 2.9vh;
	border-top: 2px solid black;
	padding: 5px;
	color: white;
	background-color: cornflowerblue;
}r'